//! Regenerate the compile-time checked format messages from the single resource table.
//! cargo run -p printcraft-ui-egui --example l10n -- --write (or --check)
use printcraft_ui_egui::i18n;
use std::io::Write;
use std::process::{Command, Stdio};
#[path = "../src/resources.rs"]
mod resources;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let output = root.join("crates/ui-egui/src/messages.rs");
    let mut generated =
        String::from("//! Generated by the l10n example from resources.rs. Do not edit by hand.\n#[macro_export]\nmacro_rules! msg {\n");
    for resource in resources::RESOURCES.iter().filter(|r| r.formatted) {
        let key = resource.key.strip_prefix("ui.").ok_or("format key must start with ui.")?;
        generated.push_str(&format!(
            "    ({key}, $($args:tt)*) => {{\n        if $crate::i18n::current() == $crate::i18n::Language::Ru {{\n            format!({:?}, $($args)*)\n        }} else {{\n            format!({:?}, $($args)*)\n        }}\n    }};\n",
            resource.ru, resource.en
        ));
    }
    generated.push_str("}\n");
    let mut formatter = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout", "--config-path"])
        .arg(&root)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .spawn()?;
    formatter.stdin.take().ok_or("missing rustfmt input")?.write_all(generated.as_bytes())?;
    let result = formatter.wait_with_output()?;
    if !result.status.success() {
        return Err("rustfmt failed".into());
    }
    match std::env::args().nth(1).as_deref() {
        Some("--write") => std::fs::write(&output, result.stdout)?,
        Some("--check") => {
            if std::fs::read(&output)? != result.stdout {
                return Err("messages.rs is stale; run l10n --write".into());
            }
        }
        _ => return Err("usage: l10n --write|--check".into()),
    }
    println!("Localization format resources: {}", resources::RESOURCES.iter().filter(|r| r.formatted).count());
    Ok(())
}
