//! Generated by the l10n example from resources.rs. Do not edit by hand.
#[macro_export]
macro_rules! msg {
    (added_value_comment_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Добавлено комментариев: {n}{}", $($args)*)
        } else {
            format!("Added {n} comment{}", $($args)*)
        }
    };
    (advanced_options_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Дополнительные параметры {chevron}", $($args)*)
        } else {
            format!("Advanced Options {chevron}", $($args)*)
        }
    };
    (applied_value_redaction_mark_value_save_to_remove_the_content_from_the_file, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Применено отметок редактирования: {marks}{}. Сохраните документ, чтобы удалить содержимое из файла.", $($args)*)
        } else {
            format!("Applied {marks} redaction mark{}. Save to remove the content from the file.", $($args)*)
        }
    };
    (applies_to_value_page_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Применяется к страницам: {n}{}", $($args)*)
        } else {
            format!("Applies to {n} page{}", $($args)*)
        }
    };
    (certified_by_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Сертифицировано: {}", $($args)*)
        } else {
            format!("Certified by {}", $($args)*)
        }
    };
    (checking_options_value_of_32_in_all_categories, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Параметры проверки ({on} из 32 во всех категориях)", $($args)*)
        } else {
            format!("Checking Options ({on} of 32 in all categories)", $($args)*)
        }
    };
    (click_on_the_page_to_add_a_value_or_drag_to_set_its_size, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Нажмите на страницу, чтобы добавить {}, или выделите область нужного размера", $($args)*)
        } else {
            format!("Click on the page to add a {}, or drag to set its size", $($args)*)
        }
    };
    (combined_value_files, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Объединено файлов: {count}", $($args)*)
        } else {
            format!("Combined {count} files", $($args)*)
        }
    };
    (coming_in_milestone_value_items_marked_ready_work_today, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Запланировано для этапа {m}. Пункты с отметкой «Готово» доступны сейчас.", $($args)*)
        } else {
            format!("Coming in milestone {m}. Items marked Ready work today.", $($args)*)
        }
    };
    (could_not_save_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось сохранить: {e}", $($args)*)
        } else {
            format!("Could not save: {e}", $($args)*)
        }
    };
    (couldn_t_add_value_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось добавить {name}: {e}", $($args)*)
        } else {
            format!("Couldn't add {name}: {e}", $($args)*)
        }
    };
    (couldn_t_check_for_updates_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось проверить обновления: {e}", $($args)*)
        } else {
            format!("Couldn't check for updates: {e}", $($args)*)
        }
    };
    (couldn_t_combine_files_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось объединить файлы: {e}", $($args)*)
        } else {
            format!("Couldn't combine files: {e}", $($args)*)
        }
    };
    (couldn_t_create_a_pdf_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось создать PDF: {e}", $($args)*)
        } else {
            format!("Couldn't create a PDF: {e}", $($args)*)
        }
    };
    (couldn_t_download_value_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось скачать {name}: {e}", $($args)*)
        } else {
            format!("Couldn't download {name}: {e}", $($args)*)
        }
    };
    (couldn_t_extract_pages_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось извлечь страницы: {e}", $($args)*)
        } else {
            format!("Couldn't extract pages: {e}", $($args)*)
        }
    };
    (couldn_t_fit_the_visible_content_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось подобрать масштаб: {e}", $($args)*)
        } else {
            format!("Couldn't fit the visible content: {e}", $($args)*)
        }
    };
    (couldn_t_open_revision_value_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось открыть версию {n}: {e}", $($args)*)
        } else {
            format!("Couldn't open revision {n}: {e}", $($args)*)
        }
    };
    (couldn_t_open_the_result_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось открыть результат: {e}", $($args)*)
        } else {
            format!("Couldn't open the result: {e}", $($args)*)
        }
    };
    (couldn_t_open_the_signed_version_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось открыть подписанную версию: {e}", $($args)*)
        } else {
            format!("Couldn't open the signed version: {e}", $($args)*)
        }
    };
    (couldn_t_open_value_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось открыть {name}: {e}", $($args)*)
        } else {
            format!("Couldn't open {name}: {e}", $($args)*)
        }
    };
    (couldn_t_open_value_value_702742, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось открыть {}: {e}", $($args)*)
        } else {
            format!("Couldn't open {}: {e}", $($args)*)
        }
    };
    (couldn_t_optimize_the_file_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось оптимизировать файл: {e}", $($args)*)
        } else {
            format!("Couldn't optimize the file: {e}", $($args)*)
        }
    };
    (couldn_t_reach_github_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось подключиться к GitHub ({e})", $($args)*)
        } else {
            format!("couldn't reach GitHub ({e})", $($args)*)
        }
    };
    (couldn_t_read_value_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось прочитать {name}: {e}", $($args)*)
        } else {
            format!("Couldn't read {name}: {e}", $($args)*)
        }
    };
    (couldn_t_read_value_value_decf41, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось прочитать {}: {e}", $($args)*)
        } else {
            format!("Couldn't read {}: {e}", $($args)*)
        }
    };
    (couldn_t_save_the_image_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось сохранить изображение: {e}", $($args)*)
        } else {
            format!("Couldn't save the image: {e}", $($args)*)
        }
    };
    (couldn_t_save_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось сохранить: {e}", $($args)*)
        } else {
            format!("Couldn't save: {e}", $($args)*)
        }
    };
    (couldn_t_save_value_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось сохранить {name}: {e}", $($args)*)
        } else {
            format!("Couldn't save {name}: {e}", $($args)*)
        }
    };
    (couldn_t_save_value_value_b552d6, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось сохранить {dest}: {e}", $($args)*)
        } else {
            format!("Couldn't save {dest}: {e}", $($args)*)
        }
    };
    (couldn_t_split_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось разделить документ: {e}", $($args)*)
        } else {
            format!("Couldn't split: {e}", $($args)*)
        }
    };
    (couldn_t_summarize_comments_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось создать сводку комментариев: {e}", $($args)*)
        } else {
            format!("Couldn't summarize comments: {e}", $($args)*)
        }
    };
    (couldn_t_use_value_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось использовать {name}: {e}", $($args)*)
        } else {
            format!("Couldn't use {name}: {e}", $($args)*)
        }
    };
    (couldn_t_write_value_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось записать {name}: {e}", $($args)*)
        } else {
            format!("Couldn't write {name}: {e}", $($args)*)
        }
    };
    (couldn_t_write_value_value_00c4f2, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось записать {}: {e}", $($args)*)
        } else {
            format!("Couldn't write {}: {e}", $($args)*)
        }
    };
    (couldn_t_write_value_value_29b5ba, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось записать {path}: {e}", $($args)*)
        } else {
            format!("Couldn't write {path}: {e}", $($args)*)
        }
    };
    (create_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Создать: {what}", $($args)*)
        } else {
            format!("Create {what}", $($args)*)
        }
    };
    (created_value_link_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Создано ссылок: {n}{}", $($args)*)
        } else {
            format!("Created {n} link{}", $($args)*)
        }
    };
    (creates_value_file_value_from_value_pages, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Будет создано файлов: {f}{} из {n} страниц.", $($args)*)
        } else {
            format!("Creates {f} file{} from {n} pages.", $($args)*)
        }
    };
    (current_page_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Текущая страница ({})", $($args)*)
        } else {
            format!("Current page ({})", $($args)*)
        }
    };
    (declared_conformance_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Заявленное соответствие: {shown}", $($args)*)
        } else {
            format!("Declared conformance: {shown}", $($args)*)
        }
    };
    (delete_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Удалить {o}", $($args)*)
        } else {
            format!("Delete {o}", $($args)*)
        }
    };
    (detected_value_form_field_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Найдено полей формы: {}{}", $($args)*)
        } else {
            format!("Detected {} form field{}", $($args)*)
        }
    };
    (digitally_signed_by_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Цифровая подпись: {name}", $($args)*)
        } else {
            format!("Digitally signed by {name}", $($args)*)
        }
    };
    (downloaded_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Скачано: {name}", $($args)*)
        } else {
            format!("Downloaded {name}", $($args)*)
        }
    };
    (downloading_attachments_on_the_web_arrives_with_m3_10_value_bytes_ready, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Для скачивания вложений используйте настольное приложение (готово байт: {})", $($args)*)
        } else {
            format!("Downloading attachments on the web arrives with M3.10 ({} bytes ready)", $($args)*)
        }
    };
    (draw_your_value_below, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Нарисуйте ниже: {what}.", $($args)*)
        } else {
            format!("Draw your {what} below.", $($args)*)
        }
    };
    (duplicate_value_onto, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Дублировать «{}» на:", $($args)*)
        } else {
            format!("Duplicate \"{}\" onto:", $($args)*)
        }
    };
    (each_file_holds_as_many_of_the_value_pages_as_fit, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Каждый файл содержит столько из {n} страниц, сколько помещается.", $($args)*)
        } else {
            format!("Each file holds as many of the {n} pages as fit.", $($args)*)
        }
    };
    (error_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Ошибка: {e}", $($args)*)
        } else {
            format!("Error: {e}", $($args)*)
        }
    };
    (example_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Пример: {}", $($args)*)
        } else {
            format!("Example: {}", $($args)*)
        }
    };
    (export_stopped_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Экспорт остановлен: {e}", $($args)*)
        } else {
            format!("Export stopped: {e}", $($args)*)
        }
    };
    (export_value_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Экспортируемое значение: {on}", $($args)*)
        } else {
            format!("Export Value: {on}", $($args)*)
        }
    };
    (exported_the_text_of_value_page_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Экспортирован текст страниц: {total}{}", $($args)*)
        } else {
            format!("Exported the text of {total} page{}", $($args)*)
        }
    };
    (exported_to_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Экспортировано в {}", $($args)*)
        } else {
            format!("Exported to {}", $($args)*)
        }
    };
    (exported_value_image_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Экспортировано изображений: {n}{}", $($args)*)
        } else {
            format!("Exported {n} image{}", $($args)*)
        }
    };
    (exported_value_image_value_bddf51, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Экспортировано изображений: {total}{}", $($args)*)
        } else {
            format!("Exported {total} image{}", $($args)*)
        }
    };
    (exporting_value_of_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Экспорт… {done} из {total}", $($args)*)
        } else {
            format!("Exporting… {done} of {total}", $($args)*)
        }
    };
    (extracted_value_page_s, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Извлечено страниц: {}", $($args)*)
        } else {
            format!("Extracted {} page(s)", $($args)*)
        }
    };
    (failed_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("; ошибок: {}", $($args)*)
        } else {
            format!("; failed: {}", $($args)*)
        }
    };
    (field_value_on_page_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Поле: {} на странице {}", $($args)*)
        } else {
            format!("Field: {} on page {}", $($args)*)
        }
    };
    (figure_value_of_value_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Изображение {} из {n}{page}", $($args)*)
        } else {
            format!("Figure {} of {n}{page}", $($args)*)
        }
    };
    (files_for_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Файлы для {}", $($args)*)
        } else {
            format!("Files for {}", $($args)*)
        }
    };
    (fixed_what_could_be_fixed_value_problem_value_remain, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Доступные исправления применены; осталось проблем: {left}{}", $($args)*)
        } else {
            format!("Fixed what could be fixed; {left} problem{} remain", $($args)*)
        }
    };
    (from_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Из {}", $($args)*)
        } else {
            format!("From {}", $($args)*)
        }
    };
    (go_to_page_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Перейти к странице {}", $($args)*)
        } else {
            format!("Go to page {}", $($args)*)
        }
    };
    (labels_value_later_pages_keep_their_labels, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Метки: {preview}. Метки последующих страниц сохраняются.", $($args)*)
        } else {
            format!("Labels: {preview}. Later pages keep their labels.", $($args)*)
        }
    };
    (merged_value_file_value_into_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Объединено файлов: {}{} в {}", $($args)*)
        } else {
            format!("Merged {} file{} into {}", $($args)*)
        }
    };
    (new_value_comments_will_look_like_this_one, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Новые комментарии типа {} будут иметь такой вид", $($args)*)
        } else {
            format!("New {} comments will look like this one", $($args)*)
        }
    };
    (no_problems_found_the_document_conforms_to_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Проблем не обнаружено: документ соответствует {}.", $($args)*)
        } else {
            format!("No problems found: the document conforms to {}.", $($args)*)
        }
    };
    (of_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("из {pages}", $($args)*)
        } else {
            format!("of {pages}", $($args)*)
        }
    };
    (of_value_3cb85d, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("из {count}", $($args)*)
        } else {
            format!("of {count}", $($args)*)
        }
    };
    (of_value_a2eabd, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("из {n}", $($args)*)
        } else {
            format!("of {n}", $($args)*)
        }
    };
    (of_value_e82ce1, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("из {}", $($args)*)
        } else {
            format!("of {}", $($args)*)
        }
    };
    (on_page_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!(" на странице {}", $($args)*)
        } else {
            format!(" on page {}", $($args)*)
        }
    };
    (one_value_file_per_page_named_after_the_document, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Один файл {} на страницу, с именем документа.", $($args)*)
        } else {
            format!("One {} file per page, named after the document.", $($args)*)
        }
    };
    (output_intent_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Условия вывода: {}", $($args)*)
        } else {
            format!("Output intent: {}", $($args)*)
        }
    };
    (page_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!(" (страница {})", $($args)*)
        } else {
            format!(" (page {})", $($args)*)
        }
    };
    (page_value_4f9c8e, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Страница {}", $($args)*)
        } else {
            format!("Page {}", $($args)*)
        }
    };
    (page_value_of_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Страница {} из {n}", $($args)*)
        } else {
            format!("Page {} of {n}", $($args)*)
        }
    };
    (pages_of_value_to_combine_e_g_1_3_6, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Страницы {} для объединения, например 1-3, 6", $($args)*)
        } else {
            format!("Pages of {} to combine, e.g. 1-3, 6", $($args)*)
        }
    };
    (planned_for_milestone_value_open_to_see_what_it_will_include, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Запланировано для этапа {m} — откройте для просмотра возможностей", $($args)*)
        } else {
            format!("Planned for milestone {m} — open to see what it will include", $($args)*)
        }
    };
    (planned_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Запланировано · {m}", $($args)*)
        } else {
            format!("Planned · {m}", $($args)*)
        }
    };
    (preview_page_value_of_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Предпросмотр: страница {} из {count}", $($args)*)
        } else {
            format!("Preview: page {} of {count}", $($args)*)
        }
    };
    (printcraft_value_is_available, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Доступна версия ФДС ПДФ {version}.", $($args)*)
        } else {
            format!("FDS PDF {version} is available.", $($args)*)
        }
    };
    (printcraft_value_is_up_to_date, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Установлена актуальная версия ФДС ПДФ {current}.", $($args)*)
        } else {
            format!("FDS PDF {current} is up to date.", $($args)*)
        }
    };
    (recognized_value_word_value_on_value_page_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Распознано слов: {words}{}; страниц: {read}{}", $($args)*)
        } else {
            format!("Recognized {words} word{} on {read} page{}", $($args)*)
        }
    };
    (recognized_value_words_in_value_file_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Распознано слов: {words}; файлов: {ok}{}", $($args)*)
        } else {
            format!("Recognized {words} words in {ok} file{}", $($args)*)
        }
    };
    (recognizing_text_file_value_of_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Распознавание текста… файл {} из {}", $($args)*)
        } else {
            format!("Recognizing text… file {} of {}", $($args)*)
        }
    };
    (recognizing_text_page_value_of_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Распознавание текста… страница {} из {}", $($args)*)
        } else {
            format!("Recognizing text… page {} of {}", $($args)*)
        }
    };
    (remove_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Удалить {}", $($args)*)
        } else {
            format!("Remove {}", $($args)*)
        }
    };
    (removed_value_hidden_item_value_save_to_remove_them_from_the_file, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Удалено скрытых элементов: {n}{}. Сохраните документ, чтобы удалить их из файла.", $($args)*)
        } else {
            format!("Removed {n} hidden item{}. Save to remove them from the file.", $($args)*)
        }
    };
    (replacement_pages_of_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Замена: страницы из {}", $($args)*)
        } else {
            format!("Replacement: pages of {}", $($args)*)
        }
    };
    (replacing_images_on_page_value_arrives_on_the_web_with_image_pickers_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Для замены изображения на странице {} используйте настольное приложение ({index})", $($args)*)
        } else {
            format!("Replacing images on page {} arrives on the web with image pickers ({index})", $($args)*)
        }
    };
    (rev_value_value_by_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Версия {}: {}, автор {}", $($args)*)
        } else {
            format!("Rev. {}: {} by {}", $($args)*)
        }
    };
    (revert_to_the_previously_saved_version_of_value_changes_since_then_can_t_be_undone_afterwards, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Вернуться к сохранённой версии «{name}»? Последующие изменения будут потеряны.", $($args)*)
        } else {
            format!("Revert to the previously saved version of \"{name}\"? Changes since then can't be undone afterwards.", $($args)*)
        }
    };
    (running_action_file_value_of_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Выполнение действия… файл {} из {}", $($args)*)
        } else {
            format!("Running action… file {} of {}", $($args)*)
        }
    };
    (save_changes_to_value_before_closing, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Сохранить изменения в «{name}» перед закрытием?", $($args)*)
        } else {
            format!("Save changes to “{name}” before closing?", $($args)*)
        }
    };
    (saved_but_reopening_failed_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Сохранено, но повторное открытие не удалось: {e}", $($args)*)
        } else {
            format!("Saved, but reopening failed: {e}", $($args)*)
        }
    };
    (saved_the_print_ready_pdf_to_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("PDF для печати сохранён в {}", $($args)*)
        } else {
            format!("Saved the print-ready PDF to {}", $($args)*)
        }
    };
    (saved_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Сохранено: {}", $($args)*)
        } else {
            format!("Saved {}", $($args)*)
        }
    };
    (saved_value_value_value_value_smaller_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Сохранено {place}: {} → {} (меньше на {pct:.0}%){detail}", $($args)*)
        } else {
            format!("Saved {place}: {} → {} ({pct:.0}% smaller){detail}", $($args)*)
        }
    };
    (searching_value_of_value_pages, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Поиск… {searched} из {pages} страниц", $($args)*)
        } else {
            format!("Searching… {searched} of {pages} pages", $($args)*)
        }
    };
    (searching_value_of_value_pages_34ed86, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!(" (поиск… {searched} из {pages} страниц)", $($args)*)
        } else {
            format!(" (searching… {searched} of {pages} pages)", $($args)*)
        }
    };
    (searching_value_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Поиск… {searched}/{pages}", $($args)*)
        } else {
            format!("Searching… {searched}/{pages}", $($args)*)
        }
    };
    (sent_to_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Отправлено на {printer}", $($args)*)
        } else {
            format!("Sent to {printer}", $($args)*)
        }
    };
    (sent_to_value_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Отправлено на {printer}: {msg}", $($args)*)
        } else {
            format!("Sent to {printer}: {msg}", $($args)*)
        }
    };
    (set_to_current_page_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Привязать к текущей странице ({})", $($args)*)
        } else {
            format!("Set to current page ({})", $($args)*)
        }
    };
    (sheet_value_of_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Лист {} из {n}", $($args)*)
        } else {
            format!("Sheet {} of {n}", $($args)*)
        }
    };
    (ships_in_milestone_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("запланировано для этапа {m}", $($args)*)
        } else {
            format!("ships in milestone {m}", $($args)*)
        }
    };
    (signed_and_saved_to_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Подписано и сохранено в {}", $($args)*)
        } else {
            format!("Signed and saved to {}", $($args)*)
        }
    };
    (strength_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Надёжность: {s}", $($args)*)
        } else {
            format!("Strength: {s}", $($args)*)
        }
    };
    (that_didn_t_work_an_internal_error_stopped_it_value_your_documents_are_unchanged, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось выполнить действие из-за внутренней ошибки ({m}). Документы не изменены.", $($args)*)
        } else {
            format!("That didn't work: an internal error stopped it ({m}). Your documents are unchanged.", $($args)*)
        }
    };
    (the_checker_found_value_problem_value_which_may_prevent_the_document_from_being_fully_accessible, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Обнаружено проблем: {failed}{}. Они могут препятствовать полной доступности документа.", $($args)*)
        } else {
            format!("The checker found {failed} problem{} which may prevent the document from being fully accessible.", $($args)*)
        }
    };
    (the_document_now_conforms_to_value_save_it_to_keep_the_changes, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Документ соответствует {}; сохраните изменения", $($args)*)
        } else {
            format!("The document now conforms to {}; save it to keep the changes", $($args)*)
        }
    };
    (the_form_asks_to_be_submitted_to_value_printcraft_doesn_t_send_form_data_save_the_document_to_keep_your_entries, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Форма запрашивает отправку на {u}; ФДС ПДФ не отправляет данные форм. Сохраните документ, чтобы сохранить введённые значения.", $($args)*)
        } else {
            format!("The form asks to be submitted to {u}; FDS PDF doesn't send form data. Save the document to keep your entries.", $($args)*)
        }
    };
    (the_keychain_s_digital_ids_couldn_t_be_listed_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось получить цифровые удостоверения из связки ключей: {e}", $($args)*)
        } else {
            format!("The Keychain's digital IDs couldn't be listed: {e}", $($args)*)
        }
    };
    (this_document_contains_value_interactive_form_fields, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Интерактивных полей формы в документе: {}.", $($args)*)
        } else {
            format!("This document contains {} interactive form fields.", $($args)*)
        }
    };
    (this_document_has_no_value_to_change, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("В документе нет {} для изменения", $($args)*)
        } else {
            format!("This document has no {} to change", $($args)*)
        }
    };
    (this_page_couldn_t_be_displayed_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось отобразить страницу.\n{err}", $($args)*)
        } else {
            format!("This page couldn't be displayed.\n{err}", $($args)*)
        }
    };
    (to_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("до {}", $($args)*)
        } else {
            format!("to {}", $($args)*)
        }
    };
    (top_level_bookmarks_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Закладки верхнего уровня ({})", $($args)*)
        } else {
            format!("Top-level bookmarks ({})", $($args)*)
        }
    };
    (type_your_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Введите: {what}.", $($args)*)
        } else {
            format!("Type your {what}.", $($args)*)
        }
    };
    (unreadable_answer_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось прочитать ответ ({e})", $($args)*)
        } else {
            format!("unreadable answer ({e})", $($args)*)
        }
    };
    (unsigned_signature_field_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Неподписанное поле подписи: {}", $($args)*)
        } else {
            format!("Unsigned signature field: {}", $($args)*)
        }
    };
    (value_action, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Действие: {s}", $($args)*)
        } else {
            format!("{s} action", $($args)*)
        }
    };
    (value_actions_run_in_the_javascript_engine_m6, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Действия {s} выполняются в движке JavaScript (M6)", $($args)*)
        } else {
            format!("{s} actions run in the JavaScript engine (M6)", $($args)*)
        }
    };
    (value_as_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{} как «{}»", $($args)*)
        } else {
            format!("{} as \"{}\"", $($args)*)
        }
    };
    (value_background, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{verb}: фон", $($args)*)
        } else {
            format!("{verb} Background", $($args)*)
        }
    };
    (value_bytes, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Байт: {n}", $($args)*)
        } else {
            format!("{n} bytes", $($args)*)
        }
    };
    (value_choosing_images_arrives_on_the_web_with_file_pickers_for_images, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{name}: для выбора изображений используйте настольное приложение", $($args)*)
        } else {
            format!("{name}: choosing images arrives on the web with file pickers for images", $($args)*)
        }
    };
    (value_click_to_show_it_on_the_page, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{} — нажмите для просмотра на странице", $($args)*)
        } else {
            format!("{} — click to show it on the page", $($args)*)
        }
    };
    (value_default, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{} (по умолчанию)", $($args)*)
        } else {
            format!("{} (default)", $($args)*)
        }
    };
    (value_difference_value_found, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Найдено различий: {n}{}", $($args)*)
        } else {
            format!("{n} difference{} found", $($args)*)
        }
    };
    (value_edited, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{name} (изменён)", $($args)*)
        } else {
            format!("{name} (edited)", $($args)*)
        }
    };
    (value_failed_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Не удалось выполнить «{label}»: {e}", $($args)*)
        } else {
            format!("{label} failed: {e}", $($args)*)
        }
    };
    (value_field, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Поле {:?}", $($args)*)
        } else {
            format!("{:?} field", $($args)*)
        }
    };
    (value_h_ago, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{} ч. назад", $($args)*)
        } else {
            format!("{} h ago", $($args)*)
        }
    };
    (value_has_no_action, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Для {} нет действия", $($args)*)
        } else {
            format!("{} has no action", $($args)*)
        }
    };
    (value_header_and_footer, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{verb}: колонтитулы", $($args)*)
        } else {
            format!("{verb} Header and Footer", $($args)*)
        }
    };
    (value_image_value_optimized, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Оптимизировано изображений: {}{}", $($args)*)
        } else {
            format!("{} image{} optimized", $($args)*)
        }
    };
    (value_instance_value_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Совпадений: {n}{}{more}", $($args)*)
        } else {
            format!("{n} instance{}{more}", $($args)*)
        }
    };
    (value_is_protected_enter_a_password_to_open_it, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("«{}» защищён. Введите пароль для открытия.", $($args)*)
        } else {
            format!("“{}” is protected. Enter a password to open it.", $($args)*)
        }
    };
    (value_is_read_only, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{} доступно только для чтения", $($args)*)
        } else {
            format!("{} is read-only", $($args)*)
        }
    };
    (value_is_too_large_for_a_stamp_at_most_value_mb, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Файл {file} слишком большой для штампа (не более {} МБ)", $($args)*)
        } else {
            format!("{file} is too large for a stamp (at most {} MB)", $($args)*)
        }
    };
    (value_issue_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Проблем: {failed}{}", $($args)*)
        } else {
            format!("{failed} issue{}", $($args)*)
        }
    };
    (value_item_value_discarded, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Удалено элементов: {discarded}{}", $($args)*)
        } else {
            format!("{discarded} item{} discarded", $($args)*)
        }
    };
    (value_kb, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{:.1} КБ", $($args)*)
        } else {
            format!("{:.1} KB", $($args)*)
        }
    };
    (value_keychain_identities_are_only_available_on_macos, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{reference}: удостоверения из связки ключей доступны только в macOS", $($args)*)
        } else {
            format!("{reference}: Keychain identities are only available on macOS", $($args)*)
        }
    };
    (value_mark_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Отметок: {marks}{}", $($args)*)
        } else {
            format!("{marks} mark{}", $($args)*)
        }
    };
    (value_match_es_marked_for_redaction, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Отмечено совпадений для удаления: {n}.", $($args)*)
        } else {
            format!("{n} match(es) marked for redaction.", $($args)*)
        }
    };
    (value_mb, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{:.1} МБ", $($args)*)
        } else {
            format!("{:.1} MB", $($args)*)
        }
    };
    (value_min_ago, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{mins} мин. назад", $($args)*)
        } else {
            format!("{mins} min ago", $($args)*)
        }
    };
    (value_not_exported_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!(" (не экспортировано: {}; {})", $($args)*)
        } else {
            format!(" ({} not exported: {})", $($args)*)
        }
    };
    (value_on_page_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{meta}  ·  на странице {}", $($args)*)
        } else {
            format!("{meta}  ·  on page {}", $($args)*)
        }
    };
    (value_page_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Страниц: {}{}", $($args)*)
        } else {
            format!("{} page{}", $($args)*)
        }
    };
    (value_page_value_already_had_text, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("; страниц с текстом: {skipped}{}", $($args)*)
        } else {
            format!("; {skipped} page{} already had text", $($args)*)
        }
    };
    (value_page_value_c4b4c2, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{} · страница {}", $($args)*)
        } else {
            format!("{} · page {}", $($args)*)
        }
    };
    (value_page_value_selected, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Выбрано страниц: {count}{}.", $($args)*)
        } else {
            format!("{count} page{} selected.", $($args)*)
        }
    };
    (value_pages, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Страниц: {}", $($args)*)
        } else {
            format!("{} pages", $($args)*)
        }
    };
    (value_pages_selected, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Выбрано страниц: {k}", $($args)*)
        } else {
            format!("{k} pages selected", $($args)*)
        }
    };
    (value_pages_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Страниц: {}  ·  {}", $($args)*)
        } else {
            format!("{} pages  ·  {}", $($args)*)
        }
    };
    (value_pixels, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{n} пикселей", $($args)*)
        } else {
            format!("{n} pixels", $($args)*)
        }
    };
    (value_pixels_inch, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{} пикселей/дюйм", $($args)*)
        } else {
            format!("{} pixels/inch", $($args)*)
        }
    };
    (value_pixels_inch_b5a63a, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{dpi} пикселей/дюйм", $($args)*)
        } else {
            format!("{dpi} pixels/inch", $($args)*)
        }
    };
    (value_properties, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Свойства: {kind}", $($args)*)
        } else {
            format!("{kind} Properties", $($args)*)
        }
    };
    (value_pt, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{} пт", $($args)*)
        } else {
            format!("{} pt", $($args)*)
        }
    };
    (value_pt_d169c6, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{size} пт", $($args)*)
        } else {
            format!("{size} pt", $($args)*)
        }
    };
    (value_signed_version, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{} (подписанная версия)", $($args)*)
        } else {
            format!("{} (signed version)", $($args)*)
        }
    };
    (value_submits_the_form_to_value_printcraft_doesn_t_send_form_data_save_the_document_to_keep_your_entries, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{name} отправляет форму на {url}; ФДС ПДФ не отправляет данные форм. Сохраните документ, чтобы сохранить введённые значения.", $($args)*)
        } else {
            format!("{name} submits the form to {url}; FDS PDF doesn't send form data. Save the document to keep your entries.", $($args)*)
        }
    };
    (value_the_value_action_isn_t_supported_yet, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{name}: действие {other} пока не поддерживается", $($args)*)
        } else {
            format!("{name}: the {other} action isn't supported yet", $($args)*)
        }
    };
    (value_to_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{msg} в {shown}", $($args)*)
        } else {
            format!("{msg} to {shown}", $($args)*)
        }
    };
    (value_to_value_aee49d, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("с {} по {}", $($args)*)
        } else {
            format!("{} to {}", $($args)*)
        }
    };
    (value_unsaved_changes, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{name} — есть несохранённые изменения", $($args)*)
        } else {
            format!("{name} — unsaved changes", $($args)*)
        }
    };
    (value_value_bytes, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{} (байт: {})", $($args)*)
        } else {
            format!("{} ({} bytes)", $($args)*)
        }
    };
    (value_value_certificate_issued_by_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{}{org}, сертификат выдан {}.", $($args)*)
        } else {
            format!("{}{org}, certificate issued by {}.", $($args)*)
        }
    };
    (value_value_file_value_done, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{}: обработано файлов: {ok}{}", $($args)*)
        } else {
            format!("{}: {ok} file{} done", $($args)*)
        }
    };
    (value_value_in, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{:.2} × {:.2} дюйма", $($args)*)
        } else {
            format!("{:.2} × {:.2} in", $($args)*)
        }
    };
    (value_value_in_3479b5, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{w:.2} × {h:.2} дюйма", $($args)*)
        } else {
            format!("{w:.2} × {h:.2} in", $($args)*)
        }
    };
    (value_value_issue_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{} (проблем: {issues}{})", $($args)*)
        } else {
            format!("{} ({issues} issue{})", $($args)*)
        }
    };
    (value_value_issued_by_value_expires_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{}{}Выдано: {}, Действует до: {}", $($args)*)
        } else {
            format!("{}{}Issued by: {}, Expires: {}", $($args)*)
        }
    };
    (value_visual, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{} визуальное сравнение", $($args)*)
        } else {
            format!("{} Visual", $($args)*)
        }
    };
    (value_watermark, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("{verb}: водяной знак", $($args)*)
        } else {
            format!("{verb} Watermark", $($args)*)
        }
    };
    (version_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Версия {}", $($args)*)
        } else {
            format!("Version {}", $($args)*)
        }
    };
    (view_revision_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Просмотр версии {n}", $($args)*)
        } else {
            format!("View revision {n}", $($args)*)
        }
    };
    (wrote_value_file_value_to_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Записано файлов: {}{} в {}", $($args)*)
        } else {
            format!("Wrote {} file{} to {}", $($args)*)
        }
    };
    (you_are_about_to_apply_value_redaction_mark_value_text_images_and_drawings_under_the_marks_and_comments_and_form_fields_that_overlap_them_are_removed_permanently, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Будет применено отметок удаления: {marks}{}. Текст, изображения и рисунки под отметками, а также пересекающиеся комментарии и поля форм будут удалены безвозвратно.", $($args)*)
        } else {
            format!("You are about to apply {marks} redaction mark{}. Text, images and drawings under the marks, and comments and form fields that overlap them, are removed permanently.", $($args)*)
        }
    };
    (you_have_version_value_all_releases_are_listed_at_value, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Установлена версия {current}. Все релизы: {RELEASES_PAGE}.", $($args)*)
        } else {
            format!("You have version {current}. All releases are listed at {RELEASES_PAGE}.", $($args)*)
        }
    };
    (you_have_version_value_download_the_new_version_from_its_release_page, $($args:tt)*) => {
        if $crate::i18n::current() == $crate::i18n::Language::Ru {
            format!("Установлена версия {current}. Скачайте новую версию со страницы релиза.", $($args)*)
        } else {
            format!("You have version {current}. Download the new version from its release page.", $($args)*)
        }
    };
}
